'use client';
import { dashboardAction } from './action-client';
import type * as module0 from '@/app/dashboard/(protected)/about/actions';
import type * as module1 from '@/app/dashboard/(protected)/case-studies/actions';
import type * as module2 from '@/app/dashboard/(protected)/education/actions';
import type * as module3 from '@/app/dashboard/(protected)/experience/actions';
import type * as module4 from '@/app/dashboard/(protected)/hero/actions';
import type * as module5 from '@/app/dashboard/(protected)/home/actions';
import type * as module6 from '@/app/dashboard/(protected)/messages/actions';
import type * as module7 from '@/app/dashboard/(protected)/personal-projects/actions';
import type * as module8 from '@/app/dashboard/(protected)/projects/actions';
import type * as module9 from '@/app/dashboard/(protected)/projects/[id]/case-study/actions';
import type * as module10 from '@/app/dashboard/(protected)/resume/actions';
import type * as module11 from '@/app/dashboard/(protected)/seed-actions';
import type * as module12 from '@/app/dashboard/(protected)/settings/actions';
import type * as module13 from '@/app/dashboard/(protected)/settings/works-category-actions';
import type * as module14 from '@/app/dashboard/(protected)/stack/actions';
import type * as module15 from '@/app/dashboard/(protected)/traffic-sources-actions';
import type * as module16 from '@/app/dashboard/(protected)/visitors-actions';

export const updateAboutSectionAction = dashboardAction<Parameters<typeof module0.updateAboutSectionAction>, Awaited<ReturnType<typeof module0.updateAboutSectionAction>>>('updateAboutSectionAction');
export const createCaseStudyAction = dashboardAction<Parameters<typeof module1.createCaseStudyAction>, Awaited<ReturnType<typeof module1.createCaseStudyAction>>>('createCaseStudyAction');
export const updateCaseStudyAction = dashboardAction<Parameters<typeof module1.updateCaseStudyAction>, Awaited<ReturnType<typeof module1.updateCaseStudyAction>>>('updateCaseStudyAction');
export const deleteCaseStudyAction = dashboardAction<Parameters<typeof module1.deleteCaseStudyAction>, Awaited<ReturnType<typeof module1.deleteCaseStudyAction>>>('deleteCaseStudyAction');
export const toggleCaseStudyPublishedAction = dashboardAction<Parameters<typeof module1.toggleCaseStudyPublishedAction>, Awaited<ReturnType<typeof module1.toggleCaseStudyPublishedAction>>>('toggleCaseStudyPublishedAction');
export const duplicateCaseStudyAction = dashboardAction<Parameters<typeof module1.duplicateCaseStudyAction>, Awaited<ReturnType<typeof module1.duplicateCaseStudyAction>>>('duplicateCaseStudyAction');
export const saveEducationAction = dashboardAction<Parameters<typeof module2.saveEducationAction>, Awaited<ReturnType<typeof module2.saveEducationAction>>>('saveEducationAction');
export const deleteEducationAction = dashboardAction<Parameters<typeof module2.deleteEducationAction>, Awaited<ReturnType<typeof module2.deleteEducationAction>>>('deleteEducationAction');
export const reorderEducationAction = dashboardAction<Parameters<typeof module2.reorderEducationAction>, Awaited<ReturnType<typeof module2.reorderEducationAction>>>('reorderEducationAction');
export const saveExperienceAction = dashboardAction<Parameters<typeof module3.saveExperienceAction>, Awaited<ReturnType<typeof module3.saveExperienceAction>>>('saveExperienceAction');
export const deleteExperienceAction = dashboardAction<Parameters<typeof module3.deleteExperienceAction>, Awaited<ReturnType<typeof module3.deleteExperienceAction>>>('deleteExperienceAction');
export const reorderExperiencesAction = dashboardAction<Parameters<typeof module3.reorderExperiencesAction>, Awaited<ReturnType<typeof module3.reorderExperiencesAction>>>('reorderExperiencesAction');
export const updateHeroAction = dashboardAction<Parameters<typeof module4.updateHeroAction>, Awaited<ReturnType<typeof module4.updateHeroAction>>>('updateHeroAction');
export const saveHomepageConfigAction = dashboardAction<Parameters<typeof module5.saveHomepageConfigAction>, Awaited<ReturnType<typeof module5.saveHomepageConfigAction>>>('saveHomepageConfigAction');
export const toggleSkillSectionVisibilityAction = dashboardAction<Parameters<typeof module5.toggleSkillSectionVisibilityAction>, Awaited<ReturnType<typeof module5.toggleSkillSectionVisibilityAction>>>('toggleSkillSectionVisibilityAction');
export const toggleSkillVisibilityAction = dashboardAction<Parameters<typeof module5.toggleSkillVisibilityAction>, Awaited<ReturnType<typeof module5.toggleSkillVisibilityAction>>>('toggleSkillVisibilityAction');
export const bulkMessageAction = dashboardAction<Parameters<typeof module6.bulkMessageAction>, Awaited<ReturnType<typeof module6.bulkMessageAction>>>('bulkMessageAction');
export const updateMessageStatusAction = dashboardAction<Parameters<typeof module6.updateMessageStatusAction>, Awaited<ReturnType<typeof module6.updateMessageStatusAction>>>('updateMessageStatusAction');
export const updateMessagePriorityAction = dashboardAction<Parameters<typeof module6.updateMessagePriorityAction>, Awaited<ReturnType<typeof module6.updateMessagePriorityAction>>>('updateMessagePriorityAction');
export const deleteMessageAction = dashboardAction<Parameters<typeof module6.deleteMessageAction>, Awaited<ReturnType<typeof module6.deleteMessageAction>>>('deleteMessageAction');
export const createPersonalProjectAction = dashboardAction<Parameters<typeof module7.createPersonalProjectAction>, Awaited<ReturnType<typeof module7.createPersonalProjectAction>>>('createPersonalProjectAction');
export const updatePersonalProjectAction = dashboardAction<Parameters<typeof module7.updatePersonalProjectAction>, Awaited<ReturnType<typeof module7.updatePersonalProjectAction>>>('updatePersonalProjectAction');
export const deletePersonalProjectAction = dashboardAction<Parameters<typeof module7.deletePersonalProjectAction>, Awaited<ReturnType<typeof module7.deletePersonalProjectAction>>>('deletePersonalProjectAction');
export const togglePersonalProjectPublishedAction = dashboardAction<Parameters<typeof module7.togglePersonalProjectPublishedAction>, Awaited<ReturnType<typeof module7.togglePersonalProjectPublishedAction>>>('togglePersonalProjectPublishedAction');
export const togglePersonalProjectFeaturedAction = dashboardAction<Parameters<typeof module7.togglePersonalProjectFeaturedAction>, Awaited<ReturnType<typeof module7.togglePersonalProjectFeaturedAction>>>('togglePersonalProjectFeaturedAction');
export const createProjectAction = dashboardAction<Parameters<typeof module8.createProjectAction>, Awaited<ReturnType<typeof module8.createProjectAction>>>('createProjectAction');
export const updateProjectAction = dashboardAction<Parameters<typeof module8.updateProjectAction>, Awaited<ReturnType<typeof module8.updateProjectAction>>>('updateProjectAction');
export const duplicateProjectAction = dashboardAction<Parameters<typeof module8.duplicateProjectAction>, Awaited<ReturnType<typeof module8.duplicateProjectAction>>>('duplicateProjectAction');
export const deleteProjectAction = dashboardAction<Parameters<typeof module8.deleteProjectAction>, Awaited<ReturnType<typeof module8.deleteProjectAction>>>('deleteProjectAction');
export const quickProjectAction = dashboardAction<Parameters<typeof module8.quickProjectAction>, Awaited<ReturnType<typeof module8.quickProjectAction>>>('quickProjectAction');
export const bulkProjectAction = dashboardAction<Parameters<typeof module8.bulkProjectAction>, Awaited<ReturnType<typeof module8.bulkProjectAction>>>('bulkProjectAction');
export const createProjectTaxonomyAction = dashboardAction<Parameters<typeof module8.createProjectTaxonomyAction>, Awaited<ReturnType<typeof module8.createProjectTaxonomyAction>>>('createProjectTaxonomyAction');
export const updateProjectTaxonomyAction = dashboardAction<Parameters<typeof module8.updateProjectTaxonomyAction>, Awaited<ReturnType<typeof module8.updateProjectTaxonomyAction>>>('updateProjectTaxonomyAction');
export const deleteProjectTaxonomyAction = dashboardAction<Parameters<typeof module8.deleteProjectTaxonomyAction>, Awaited<ReturnType<typeof module8.deleteProjectTaxonomyAction>>>('deleteProjectTaxonomyAction');
export const revalidateCaseStudyPaths = dashboardAction<Parameters<typeof module9.revalidateCaseStudyPaths>, Awaited<ReturnType<typeof module9.revalidateCaseStudyPaths>>>('revalidateCaseStudyPaths');
export const createTextResumeAction = dashboardAction<Parameters<typeof module10.createTextResumeAction>, Awaited<ReturnType<typeof module10.createTextResumeAction>>>('createTextResumeAction');
export const uploadResumeAction = dashboardAction<Parameters<typeof module10.uploadResumeAction>, Awaited<ReturnType<typeof module10.uploadResumeAction>>>('uploadResumeAction');
export const saveResumeVersionAction = dashboardAction<Parameters<typeof module10.saveResumeVersionAction>, Awaited<ReturnType<typeof module10.saveResumeVersionAction>>>('saveResumeVersionAction');
export const restoreResumeVersionAction = dashboardAction<Parameters<typeof module10.restoreResumeVersionAction>, Awaited<ReturnType<typeof module10.restoreResumeVersionAction>>>('restoreResumeVersionAction');
export const archiveResumeAction = dashboardAction<Parameters<typeof module10.archiveResumeAction>, Awaited<ReturnType<typeof module10.archiveResumeAction>>>('archiveResumeAction');
export const runAtsAnalysisAction = dashboardAction<Parameters<typeof module10.runAtsAnalysisAction>, Awaited<ReturnType<typeof module10.runAtsAnalysisAction>>>('runAtsAnalysisAction');
export const getResumeAnalyticsAction = dashboardAction<Parameters<typeof module10.getResumeAnalyticsAction>, Awaited<ReturnType<typeof module10.getResumeAnalyticsAction>>>('getResumeAnalyticsAction');
export const seedDefaultContentAction = dashboardAction<Parameters<typeof module11.seedDefaultContentAction>, Awaited<ReturnType<typeof module11.seedDefaultContentAction>>>('seedDefaultContentAction');
export const updateSettingsAction = dashboardAction<Parameters<typeof module12.updateSettingsAction>, Awaited<ReturnType<typeof module12.updateSettingsAction>>>('updateSettingsAction');
export const updateHomeContentAction = dashboardAction<Parameters<typeof module12.updateHomeContentAction>, Awaited<ReturnType<typeof module12.updateHomeContentAction>>>('updateHomeContentAction');
export const updateThemeSettingsAction = dashboardAction<Parameters<typeof module12.updateThemeSettingsAction>, Awaited<ReturnType<typeof module12.updateThemeSettingsAction>>>('updateThemeSettingsAction');
export const getWorksCategoriesConfig = dashboardAction<Parameters<typeof module13.getWorksCategoriesConfig>, Awaited<ReturnType<typeof module13.getWorksCategoriesConfig>>>('getWorksCategoriesConfig');
export const toggleWorksCategoryBarAction = dashboardAction<Parameters<typeof module13.toggleWorksCategoryBarAction>, Awaited<ReturnType<typeof module13.toggleWorksCategoryBarAction>>>('toggleWorksCategoryBarAction');
export const addWorksCategoryAction = dashboardAction<Parameters<typeof module13.addWorksCategoryAction>, Awaited<ReturnType<typeof module13.addWorksCategoryAction>>>('addWorksCategoryAction');
export const renameWorksCategoryAction = dashboardAction<Parameters<typeof module13.renameWorksCategoryAction>, Awaited<ReturnType<typeof module13.renameWorksCategoryAction>>>('renameWorksCategoryAction');
export const deleteWorksCategoryAction = dashboardAction<Parameters<typeof module13.deleteWorksCategoryAction>, Awaited<ReturnType<typeof module13.deleteWorksCategoryAction>>>('deleteWorksCategoryAction');
export const getPersonalProjectsCategoriesConfig = dashboardAction<Parameters<typeof module13.getPersonalProjectsCategoriesConfig>, Awaited<ReturnType<typeof module13.getPersonalProjectsCategoriesConfig>>>('getPersonalProjectsCategoriesConfig');
export const togglePersonalProjectsCategoryBarAction = dashboardAction<Parameters<typeof module13.togglePersonalProjectsCategoryBarAction>, Awaited<ReturnType<typeof module13.togglePersonalProjectsCategoryBarAction>>>('togglePersonalProjectsCategoryBarAction');
export const addPersonalProjectsCategoryAction = dashboardAction<Parameters<typeof module13.addPersonalProjectsCategoryAction>, Awaited<ReturnType<typeof module13.addPersonalProjectsCategoryAction>>>('addPersonalProjectsCategoryAction');
export const renamePersonalProjectsCategoryAction = dashboardAction<Parameters<typeof module13.renamePersonalProjectsCategoryAction>, Awaited<ReturnType<typeof module13.renamePersonalProjectsCategoryAction>>>('renamePersonalProjectsCategoryAction');
export const deletePersonalProjectsCategoryAction = dashboardAction<Parameters<typeof module13.deletePersonalProjectsCategoryAction>, Awaited<ReturnType<typeof module13.deletePersonalProjectsCategoryAction>>>('deletePersonalProjectsCategoryAction');
export const updateStackHeroAction = dashboardAction<Parameters<typeof module14.updateStackHeroAction>, Awaited<ReturnType<typeof module14.updateStackHeroAction>>>('updateStackHeroAction');
export const addSectionAction = dashboardAction<Parameters<typeof module14.addSectionAction>, Awaited<ReturnType<typeof module14.addSectionAction>>>('addSectionAction');
export const updateSectionAction = dashboardAction<Parameters<typeof module14.updateSectionAction>, Awaited<ReturnType<typeof module14.updateSectionAction>>>('updateSectionAction');
export const deleteSectionAction = dashboardAction<Parameters<typeof module14.deleteSectionAction>, Awaited<ReturnType<typeof module14.deleteSectionAction>>>('deleteSectionAction');
export const addSkillAction = dashboardAction<Parameters<typeof module14.addSkillAction>, Awaited<ReturnType<typeof module14.addSkillAction>>>('addSkillAction');
export const updateSkillAction = dashboardAction<Parameters<typeof module14.updateSkillAction>, Awaited<ReturnType<typeof module14.updateSkillAction>>>('updateSkillAction');
export const deleteSkillAction = dashboardAction<Parameters<typeof module14.deleteSkillAction>, Awaited<ReturnType<typeof module14.deleteSkillAction>>>('deleteSkillAction');
export const getTrafficSourcesDataAction = dashboardAction<Parameters<typeof module15.getTrafficSourcesDataAction>, Awaited<ReturnType<typeof module15.getTrafficSourcesDataAction>>>('getTrafficSourcesDataAction');
export const getVisitorsPopupDataAction = dashboardAction<Parameters<typeof module16.getVisitorsPopupDataAction>, Awaited<ReturnType<typeof module16.getVisitorsPopupDataAction>>>('getVisitorsPopupDataAction');
